tls:
  options:
    default: # Default tls options will be used by defaults !
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_FALLBACK_SCSV # This ensure to try 
# TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_AES_128_GCM_SHA256
# TLS 1.2
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256  # This one is weak but required to allow communication with old IE versions and old Safari
    strict:
      minVersion: VersionTLS13
      sniStric: true
      cipherSuites:
        - TLS_FALLBACK_SCSV
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384